name: Publish

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  default:
    name: Publish Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.14.0'

      - name: Setup PNPM
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.5.4
          run_install: |
            - args: [--frozen-lockfile, --silent]
      - name: Build Packages
        run: |
          pnpm build
      - name: Publish Insiders Extension
        run: |
          pnpm recursive --filter ./extension run release
        env:
          VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCE_TOKEN }}
